<?php

namespace Database\Seeders;

use App\Models\Blog;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::pluck('id', 'slug')->toArray();

        $blogs = [
            [
                'category_id' => $categories['saas-cloud-apps'] ?? null,
                'title' => 'Architecting High-Throughput Micro-Frontends with React 19 and Inertia',
                'slug' => 'architecting-high-throughput-micro-frontends-react-19',
                'short_description' => 'A deep dive into building modular, lightning-fast enterprise web architectures combining server-driven routing with modern React 19 capabilities.',
                'content' => '<h2>The Evolution of Modern Web Applications</h2><p>Modern enterprise web applications require a delicate balance between engineering speed, runtime performance, and maintainable modular architecture. In recent years, monolithic frontends have increasingly caused build bottlenecks, while excessive micro-frontend fragmentation has introduced runtime overhead.</p><h3>Why Inertia.js with React 19 Changes the Paradigm</h3><p>By pairing <strong>Laravel on the backend with React 19 on the client</strong>, we eliminate the traditional dual-API maintenance burden while preserving the fluid, instant user experience of a Single Page Application (SPA).</p><blockquote><p>“Speed and clarity are not trade-offs; with modern compiler optimizations, they reinforce each other.”</p></blockquote><ul><li><strong>Zero-latency SPA Transitions:</strong> Inertia handles client-side routing with automatic JSON payload diffs.</li><li><strong>React 19 Actions & Concurrent Mode:</strong> Seamless background state transitions without UI freezing.</li><li><strong>Tailwind CSS v4 Engine:</strong> Ultra-fast compilation and custom CSS variable tokens.</li></ul><h3>Real-world Benchmarks</h3><p>In our client implementations, transitioning to this architecture resulted in an <strong>82% reduction in initial payload size</strong> and improved Core Web Vitals to a sustained 99+ score across mobile and desktop viewports.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Alexander Vance',
                'author_role' => 'Principal Software Architect',
                'author_avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
                'tags' => ['React 19', 'Architecture', 'Inertia.js', 'Performance', 'Laravel'],
                'reads_count' => 1420,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subHours(8),
                'order' => 1,
            ],
            [
                'category_id' => $categories['ai-intelligent-systems'] ?? null,
                'title' => 'Engineering Autonomous AI Agents with Streaming Workflows and Vector DBs',
                'slug' => 'engineering-autonomous-ai-agents-vector-dbs',
                'short_description' => 'How to design deterministic, low-latency AI tool orchestration with semantic vector memory and real-time Server-Sent Events (SSE).',
                'content' => '<h2>Bridging LLM Intelligence with Enterprise Determinism</h2><p>Large Language Models alone are not sufficient for mission-critical enterprise workflows. To build resilient AI agents, software architects must build robust guardrails, token stream parsers, and semantic caching layers.</p><h3>Key Architectural Pillars</h3><ol><li><strong>Vector Indexing with Hybrid Search:</strong> Combining dense semantic vectors with BM25 sparse keyword queries ensures maximum recall accuracy.</li><li><strong>Streaming Token Pipelines:</strong> Delivering immediate perceptual response times via SSE streaming.</li><li><strong>Fault-tolerant Tool Calling:</strong> Schema validation with strict JSON schemas prevents hallucinations.</li></ol><blockquote><p>“An AI agent is only as good as its underlying deterministic fallback systems.”</p></blockquote><h3>Observability and Telemetry</h3><p>We implement end-to-end token auditing and latency tracing at every prompt generation step to guarantee SLAs under heavy enterprise loads.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Dr. Elena Rostova',
                'author_role' => 'Head of AI Engineering',
                'author_avatar' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
                'tags' => ['AI', 'LLM', 'Vector DB', 'Machine Learning', 'Python'],
                'reads_count' => 1280,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subDays(1),
                'order' => 2,
            ],
            [
                'category_id' => $categories['e-commerce-platforms'] ?? null,
                'title' => 'Next-Generation Headless E-Commerce: Sub-Second Checkout at Scale',
                'slug' => 'next-gen-headless-ecommerce-sub-second-checkout',
                'short_description' => 'Scaling global multi-currency checkout funnels with edge caching, atomic inventory locks, and distributed payment orchestration.',
                'content' => '<h2>The Cost of Millisecond Latency in Digital Commerce</h2><p>Every 100ms of latency during checkout translates directly to an 8% drop in final order conversion rates. In this technical breakdown, we explore how edge caching and distributed transactional locks guarantee instantaneous cart reconciliation.</p><h3>Techniques for High-Volume Flash Sales</h3><ul><li><strong>Optimistic Inventory Reservation:</strong> Redis Lua scripts handle 50,000+ checkout operations per second without database lock contention.</li><li><strong>Edge Compute Middleware:</strong> Geo-routing shoppers to the nearest CDN edge node for instant cart calculations.</li><li><strong>Stripe & PayPal Webhook Orchestration:</strong> Idempotent background queues with automatic exponential backoff retry policies.</li></ul><p>By decoupling frontend catalog presentation from backend transaction processing, high-volume merchants ensure zero downtime during global product launches.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Marcus Sterling',
                'author_role' => 'Senior Solutions Architect',
                'author_avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
                'tags' => ['E-Commerce', 'Redis', 'Checkout', 'Stripe', 'High Performance'],
                'reads_count' => 945,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(2),
                'order' => 3,
            ],
            [
                'category_id' => $categories['modern-landing-pages'] ?? null,
                'title' => 'Mastering Glassmorphism, Micro-Interactions, and AOS Scroll Choreography',
                'slug' => 'mastering-glassmorphism-micro-interactions-aos',
                'short_description' => 'Transforming static web interfaces into dynamic, immersive digital brand experiences using hardware-accelerated CSS and viewport scroll triggers.',
                'content' => '<h2>Elevating Modern UI Design into an Immersive Experience</h2><p>Great web design communicates brand authority within the first 3 seconds of a visitor landing on the page. Combining translucent backdrop blurs, organic glowing gradients, and choreographed scroll entrances creates an undeniable feeling of quality.</p><h3>Key Animation Principles</h3><ul><li><strong>GPU-Accelerated Transforms:</strong> Use <code>transform: translate3d()</code> and <code>opacity</code> to maintain a rock-solid 60fps frame rate.</li><li><strong>Staggered Scroll Triggers:</strong> Employing AOS delay chains (e.g. 100ms, 200ms, 300ms) leads the user’s eye naturally through the information hierarchy.</li><li><strong>Adaptive Dark/Light Contrast:</strong> Ensure all translucent glass surfaces adjust their border and shadow intensities dynamically based on the current theme token.</li></ul><p>When micro-animations respond intuitively to user intent, user engagement metrics and session duration increase significantly.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Sophia Lin',
                'author_role' => 'Lead UI/UX Designer',
                'author_avatar' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop',
                'tags' => ['UI/UX', 'AOS', 'Animations', 'Tailwind CSS', 'Design System'],
                'reads_count' => 1890,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subDays(3),
                'order' => 4,
            ],
            [
                'category_id' => $categories['saas-cloud-apps'] ?? null,
                'title' => 'PostgreSQL at Scale: Partitioning, PgBouncer Pooling, and Zero-Downtime Migrations',
                'slug' => 'postgresql-at-scale-partitioning-pgbouncer-migrations',
                'short_description' => 'Architecting relational storage for millions of daily active users with declarative partitioning, transaction pooling, and safe table alteration strategies.',
                'content' => '<h2>Managing High-Velocity Relational Data</h2><p>As SaaS applications grow past billions of rows, unindexed queries and lock contention can quickly cripple application throughput. By introducing declarative range partitioning, time-series telemetry data query times drop from minutes to single-digit milliseconds.</p><h3>High-Concurreny Pooling with PgBouncer</h3><p>Direct connections to Postgres consume substantial memory overhead per worker process. Placing PgBouncer in transaction pooling mode allows thousands of web workers to share a compact, highly optimized database connection pool.</p><h3>Safe Schema Migrations</h3><p>We implement a strict 5-step expansion and contraction migration pattern, ensuring columns are added with null safety, backfilled asynchronously, and constraints validated without locking active production tables.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'David Kim',
                'author_role' => 'Senior Database Engineer',
                'author_avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
                'tags' => ['PostgreSQL', 'Database', 'PgBouncer', 'High Availability', 'Backend'],
                'reads_count' => 820,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(4),
                'order' => 5,
            ],
            [
                'category_id' => $categories['custom-web-portals'] ?? null,
                'title' => 'Building Real-Time Multi-User Collaboration Workspaces with WebSockets and CRDTs',
                'slug' => 'real-time-collaboration-workspaces-websockets-crdts',
                'short_description' => 'Implementing conflict-free collaborative editing, presence indicators, and live cursor tracking in browser-based workflow canvases.',
                'content' => '<h2>The Technology Behind Seamless Multi-User Collaboration</h2><p>Users expect modern cloud tools to allow concurrent editing without overwriting changes. Conflict-Free Replicated Data Types (CRDTs) mathematically guarantee eventual consistency across all distributed clients without central lock servers.</p><h3>Optimizing WebSocket Channels</h3><p>By batching delta diffs and leveraging binary protobuf encoding over raw JSON, we achieved an <strong>80% bandwidth saving</strong> for live collaborative canvas operations.</p><ul><li><strong>Presence State Broadcasting:</strong> Lightweight heartbeat payloads broadcast cursor coordinates at 60hz.</li><li><strong>Offline Reconnection Buffering:</strong> Local IndexedDB changes seamlessly merge upon reconnecting to the network.</li></ul>',
                'thumbnail' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Sarah Jenkins',
                'author_role' => 'Lead Frontend Engineer',
                'author_avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
                'tags' => ['WebSockets', 'Real-time', 'CRDT', 'Collaboration', 'Node.js'],
                'reads_count' => 1150,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subDays(5),
                'order' => 6,
            ],
            [
                'category_id' => $categories['fintech-web3'] ?? null,
                'title' => 'Zero-Trust Security Architecture for Modern Cloud APIs and Web Applications',
                'slug' => 'zero-trust-security-architecture-cloud-apis',
                'short_description' => 'Implementing mutual TLS, asymmetric JWT token signing, and automated threat mitigation pipelines in financial web architectures.',
                'content' => '<h2>Moving Beyond Perimeter-Based Security</h2><p>In a distributed cloud environment, the traditional firewall perimeter model is obsolete. Zero-Trust operates on the principle of <em>never trust, always verify</em>, validating every request across identity, device health, and cryptographic signatures.</p><h3>Core Security Implementations</h3><ol><li><strong>mTLS Between Internal Services:</strong> Every internal microservice-to-microservice communication is mutually authenticated and encrypted with short-lived certificates.</li><li><strong>Hardware-Backed MFA & Passkeys:</strong> Eliminating phishing vulnerabilities via WebAuthn and FIDO2 standards.</li><li><strong>Continuous Audit Logging:</strong> Immutable append-only audit streams sent to isolated SOC-compliant data lakes.</li></ol>',
                'thumbnail' => 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Michael Torres',
                'author_role' => 'Chief Information Security Officer',
                'author_avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop',
                'tags' => ['Security', 'Zero Trust', 'OAuth2', 'Cryptography', 'DevSecOps'],
                'reads_count' => 930,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(6),
                'order' => 7,
            ],
            [
                'category_id' => $categories['saas-cloud-apps'] ?? null,
                'title' => 'Optimizing Edge Latency with Cloudflare Workers, KV Caching, and Geo-Routing',
                'slug' => 'optimizing-edge-latency-cloudflare-workers-kv-caching',
                'short_description' => 'How to serve dynamic web requests in under 15ms globally by moving compute and key-value state directly to edge data centers.',
                'content' => '<h2>Bringing Computation to the User’s Doorstep</h2><p>Traditional centralized servers in a single AWS region impose 150ms+ round-trip latency for international users. By executing lightweight V8 isolates at 300+ global edge locations, server response time is effectively decoupled from geographical distance.</p><h3>Edge-Rendered Dynamic Personalization</h3><p>Using Cloudflare Workers and global KV stores, user authorization checks, feature flags, and localization occur within 10ms before requests ever hit origin servers.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Liam O\'Connor',
                'author_role' => 'DevOps & Edge Specialist',
                'author_avatar' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop',
                'tags' => ['Cloudflare', 'Edge Computing', 'CDN', 'Web Performance', 'Serverless'],
                'reads_count' => 770,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(7),
                'order' => 8,
            ],
            [
                'category_id' => $categories['modern-landing-pages'] ?? null,
                'title' => 'Designing High-Converting B2B SaaS Landing Pages that Drive $10M+ ARR',
                'slug' => 'designing-high-converting-b2b-saas-landing-pages',
                'short_description' => 'The exact design framework, visual hierarchy, and interactive product demo patterns used by industry-leading software unicorns.',
                'content' => '<h2>The Anatomy of a High-Conversion Hero Section</h2><p>B2B buyers evaluate your software solution in seconds. Top-tier SaaS landing pages combine an unmistakable value proposition, interactive live product sandbox previews, and prominent social proof above the fold.</p><h3>Key Conversion Drivers</h3><ul><li><strong>Interactive Interactive Component Demos:</strong> Letting users click and experience software features directly on the landing page boosts trial signups by 34%.</li><li><strong>Trust Badges and Real Customer Metrics:</strong> Displaying verified review counts (e.g. Trustpilot 4.9/5) and named customer logos eliminates enterprise hesitation.</li><li><strong>Frictionless Call-to-Action Flows:</strong> One-click Google/GitHub OAuth sign-in workflows without lengthy multi-page forms.</li></ul>',
                'thumbnail' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Emily Zhang',
                'author_role' => 'Product Growth Strategist',
                'author_avatar' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
                'tags' => ['Growth', 'Landing Page', 'Conversion Rate', 'UX Design', 'Copywriting'],
                'reads_count' => 2100,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subDays(8),
                'order' => 9,
            ],
            [
                'category_id' => $categories['custom-web-portals'] ?? null,
                'title' => 'Enterprise Domain-Driven Design (DDD) with Clean Architecture in Laravel 12',
                'slug' => 'enterprise-domain-driven-design-clean-architecture-laravel',
                'short_description' => 'Structuring complex business domains into decoupled bounded contexts, immutable value objects, and testable domain events.',
                'content' => '<h2>Taming Complexity in Massive Codebases</h2><p>As enterprise web apps scale beyond hundreds of database tables, standard MVC controllers and model fatness quickly become unmaintainable. Domain-Driven Design (DDD) partitions application logic into clearly defined Bounded Contexts.</p><h3>Structuring Bounded Contexts</h3><p>We separate our domain models from database Eloquent persistence layers using repository interfaces, command buses, and domain event dispatchers. This allows independent domain testing with zero database IO overhead.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Jonathan Hayes',
                'author_role' => 'Enterprise Software Consultant',
                'author_avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
                'tags' => ['Laravel', 'DDD', 'Clean Architecture', 'PHP', 'Design Patterns'],
                'reads_count' => 1040,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(9),
                'order' => 10,
            ],
            [
                'category_id' => $categories['fintech-web3'] ?? null,
                'title' => 'Institutional Crypto Trading Engines: Sub-Millisecond Order Routing & FIX Protocol',
                'slug' => 'institutional-crypto-trading-engines-sub-millisecond-routing',
                'short_description' => 'Building deterministic matching engines and low-latency order routing networks capable of handling 500,000 orders per second.',
                'content' => '<h2>The High-Frequency Financial Engineering Challenge</h2><p>Institutional digital asset trading requires microsecond determinism and zero packet loss. We explore the architectural principles behind memory-mapped order books, FIX (Financial Information eXchange) protocol adapters, and non-blocking asynchronous event loops.</p><h3>Optimizing Memory Allocation</h3><p>By avoiding runtime garbage collection pauses and implementing fixed-size circular ring buffers, matching engine latency variance is kept under 50 microseconds even during market volatility spikes.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Viktor Kasparov',
                'author_role' => 'FinTech Systems Architect',
                'author_avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
                'tags' => ['FinTech', 'Trading', 'FIX Protocol', 'Low Latency', 'Blockchain'],
                'reads_count' => 890,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(10),
                'order' => 11,
            ],
            [
                'category_id' => $categories['saas-cloud-apps'] ?? null,
                'title' => 'Next-Level TypeScript: Template Literal Types, Zod, and End-to-End Type Safety',
                'slug' => 'next-level-typescript-template-literal-types-zod',
                'short_description' => 'How to eliminate runtime bugs and achieve automatic type inference from database schema to React components.',
                'content' => '<h2>Why End-to-End Type Safety Matters</h2><p>Type mismatches between client forms and backend database contracts are the leading cause of production runtime errors. Combining TypeScript advanced conditional types with runtime validation libraries like Zod creates an unbreakable compile-time contract.</p><h3>Automatic Schema Generation</h3><p>We generate client-side TypeScript interfaces directly from database models and backend route definitions, giving engineers instant auto-completion and compile-time validation for all API inputs and Inertia props.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1516116211227-bbc13c749969?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Nathan Reed',
                'author_role' => 'Principal TypeScript Engineer',
                'author_avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop',
                'tags' => ['TypeScript', 'Zod', 'Full Stack', 'Developer Experience', 'Node.js'],
                'reads_count' => 1630,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subDays(11),
                'order' => 12,
            ],
            [
                'category_id' => $categories['e-commerce-platforms'] ?? null,
                'title' => 'Modern Multi-Storefront Inventory Synchronization Across Global Warehouses',
                'slug' => 'multi-storefront-inventory-synchronization-global-warehouses',
                'short_description' => 'Architecting real-time event-driven stock synchronization across Amazon, Shopify, custom mobile apps, and retail POS terminals.',
                'content' => '<h2>Solving the Omnichannel Overselling Dilemma</h2><p>When high-demand items are sold concurrently across multiple marketplaces, split-second inventory race conditions can result in customer cancellations and marketplace penalties. An event-driven architecture using Kafka message buses guarantees global synchronization in real time.</p><h3>Event Sourcing & Dead-Letter Queues</h3><p>By recording every stock mutation as an immutable ledger event, any network partition or third-party API outage can be replayed cleanly with zero manual intervention.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Olivia Bennett',
                'author_role' => 'Supply Chain & Tech Lead',
                'author_avatar' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop',
                'tags' => ['E-Commerce', 'Logistics', 'Inventory', 'GraphQL', 'Automation'],
                'reads_count' => 690,
                'is_featured' => false,
                'is_published' => true,
                'published_at' => now()->subDays(13),
                'order' => 13,
            ],
            [
                'category_id' => $categories['modern-landing-pages'] ?? null,
                'title' => 'Demystifying Core Web Vitals in 2026: INP, LCP Optimization and Island Architecture',
                'slug' => 'demystifying-core-web-vitals-inp-lcp-optimization',
                'short_description' => 'A practical, actionable engineering guide to passing Google Interaction to Next Paint (INP) and Largest Contentful Paint (LCP) benchmarks.',
                'content' => '<h2>Understanding the Interaction to Next Paint (INP) Standard</h2><p>Google’s Core Web Vitals metric, INP, measures the responsiveness of every user interaction on a webpage. Heavy JavaScript thread blocking causes noticeable input delays that directly hurt search rankings.</p><h3>Key Remediation Strategies</h3><ul><li><strong>Yielding to the Main Thread:</strong> Breaking long tasks into micro-chunks with <code>scheduler.yield()</code> ensures browser clicks respond instantaneously.</li><li><strong>Critical Asset Preloading:</strong> Priority hinting hero images with <code>fetchpriority="high"</code> cuts LCP times by over 40%.</li><li><strong>CSS Containment:</strong> Using <code>contain: content</code> allows the browser engine to skip off-screen layout calculations.</li></ul>',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
                'author_name' => 'Lucas Silva',
                'author_role' => 'Web Performance Evangelist',
                'author_avatar' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop',
                'tags' => ['Core Web Vitals', 'INP', 'LCP', 'Performance', 'SEO'],
                'reads_count' => 1750,
                'is_featured' => true,
                'is_published' => true,
                'published_at' => now()->subDays(14),
                'order' => 14,
            ],
        ];

        foreach ($blogs as $blog) {
            Blog::updateOrCreate(
                ['slug' => $blog['slug']],
                $blog
            );
        }
    }
}
