<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Portfolio;
use Illuminate\Database\Seeder;

class PortfolioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $saas = Category::where('slug', 'saas-cloud-apps')->first()?->id;
        $ecom = Category::where('slug', 'e-commerce-platforms')->first()?->id;
        $ai = Category::where('slug', 'ai-intelligent-systems')->first()?->id;
        $fintech = Category::where('slug', 'fintech-web3')->first()?->id;
        $portals = Category::where('slug', 'custom-web-portals')->first()?->id;
        $landing = Category::where('slug', 'modern-landing-pages')->first()?->id;

        $portfolios = [
            [
                'category_id' => $saas,
                'title' => 'NexusCloud Enterprise Platform',
                'slug' => 'nexuscloud-enterprise-platform',
                'short_description' => 'Multi-tenant cloud infrastructure monitoring platform with real-time telemetry, automated scaling triggers, and team collaboration.',
                'description' => '<h3>About NexusCloud</h3><p>NexusCloud was engineered to streamline distributed cloud management for high-velocity DevOps engineering squads. With sub-second telemetry aggregation, multi-cloud Kubernetes cluster insights, and granular RBAC permissions, NexusCloud serves over 40,000 daily engineers.</p><h4>Key Engineering Highlights</h4><ul><li>Sub-50ms query response time across billions of metric time-series points.</li><li>Dynamic visual pipeline orchestrator using React Flow and WebSockets.</li><li>End-to-end encrypted audit logging and multi-region failover.</li></ul>',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://nexuscloud.example.io',
                'youtube_video_url' => 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
                'client_name' => 'Nexus Global Inc.',
                'completion_date' => 'May 2026',
                'tech_stacks' => ['React', 'Inertia.js', 'Laravel 12', 'Tailwind CSS', 'Redis', 'PostgreSQL'],
                'views_count' => 1420,
                'is_featured' => true,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'category_id' => $ai,
                'title' => 'CognitiveAI Copilot Workspace',
                'slug' => 'cognitiveai-copilot-workspace',
                'short_description' => 'Autonomous multi-model AI agent platform featuring real-time streaming LLM orchestration, vector search knowledge graph, and code intelligence.',
                'description' => '<h3>Transforming Enterprise Workflows with Autonomous Intelligence</h3><p>CognitiveAI brings cutting-edge generative AI capabilities into secure internal team workflows. Connect private knowledge bases, run local or cloud LLMs, and build visual agent graphs with one click.</p><h4>Core Architecture</h4><ul><li>Streaming SSE integration for zero-latency LLM responses.</li><li>RAG pipeline powered by pgvector and hybrid keyword search.</li><li>Interactive artifact live canvas with split view code execution.</li></ul>',
                'thumbnail' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://cognitiveai.example.com',
                'youtube_video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'client_name' => 'Synthetix Labs',
                'completion_date' => 'June 2026',
                'tech_stacks' => ['Next.js', 'TypeScript', 'Tailwind CSS', 'OpenAI API', 'Python', 'FastAPI'],
                'views_count' => 2180,
                'is_featured' => true,
                'order' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $ecom,
                'title' => 'Aura Luxury Apparel Global Store',
                'slug' => 'aura-luxury-apparel-global-store',
                'short_description' => 'Headless e-commerce flagship with 3D product previews, multi-currency localization, one-click checkout, and AI fit recommendation.',
                'description' => '<h3>High Fashion Meets Headless Performance</h3><p>Built for luxury European fashion label Aura, this platform delivers 99+ Google Lighthouse performance scores, instant page transitions, and a 38% increase in global conversion rates.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://aurafashion.example.com',
                'youtube_video_url' => 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
                'client_name' => 'Aura Maison Paris',
                'completion_date' => 'March 2026',
                'tech_stacks' => ['Shopify Plus', 'React', 'Tailwind CSS', 'GraphQL', 'Stripe'],
                'views_count' => 970,
                'is_featured' => true,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'category_id' => $fintech,
                'title' => 'VortexPay Institutional Banking Terminal',
                'slug' => 'vortexpay-institutional-banking-terminal',
                'short_description' => 'Cross-border B2B settlement gateway supporting 40+ fiat currencies and instant stablecoin liquidity corridors.',
                'description' => '<h3>Next-Generation Financial Infrastructure</h3><p>VortexPay processes over $50M daily in cross-border settlements with institutional compliance, automated AML screening, and automated FX hedging.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'direct_link',
                'direct_url' => 'https://stripe.com',
                'youtube_video_url' => null,
                'client_name' => 'Vortex Financial Group',
                'completion_date' => 'April 2026',
                'tech_stacks' => ['Laravel', 'Vue.js', 'PostgreSQL', 'Docker', 'AWS'],
                'views_count' => 1650,
                'is_featured' => true,
                'order' => 4,
                'is_active' => true,
            ],
            [
                'category_id' => $landing,
                'title' => 'CyberPulse 3D Interactive Showreel',
                'slug' => 'cyberpulse-3d-interactive-showreel',
                'short_description' => 'Award-winning WebGL interactive showcase with dynamic particle simulations, smooth scroll typography, and immersive soundscapes.',
                'description' => '<h3>Pushing the Boundaries of Web Experiences</h3><p>Created for an international tech festival, CyberPulse combines Three.js shaders with buttery-smooth GSAP scroll animations.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://cyberpulse.example.dev',
                'youtube_video_url' => 'https://www.youtube.com/watch?v=9bZkp7q19f0',
                'client_name' => 'CyberPulse Expo',
                'completion_date' => 'February 2026',
                'tech_stacks' => ['Three.js', 'React Three Fiber', 'GSAP', 'Tailwind CSS'],
                'views_count' => 3120,
                'is_featured' => true,
                'order' => 5,
                'is_active' => true,
            ],
            [
                'category_id' => $portals,
                'title' => 'OmniCare Healthcare Provider Portal',
                'slug' => 'omnicare-healthcare-provider-portal',
                'short_description' => 'HIPAA-compliant telehealth clinical management system with digital prescriptions, real-time video consults, and EHR synchronization.',
                'description' => '<h3>Streamlining Patient Care at Scale</h3><p>OmniCare connects over 2,000 medical practitioners with hospital networks, providing unified diagnostic imaging review and secure patient records management.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://omnicare.example.health',
                'youtube_video_url' => null,
                'client_name' => 'OmniCare Health Network',
                'completion_date' => 'January 2026',
                'tech_stacks' => ['Laravel 12', 'Inertia.js', 'React', 'WebRTC', 'MySQL'],
                'views_count' => 840,
                'is_featured' => true,
                'order' => 6,
                'is_active' => true,
            ],
            [
                'category_id' => $saas,
                'title' => 'PulseMetrics Real-Time SEO & App Analytics',
                'slug' => 'pulsemetrics-real-time-seo-app-analytics',
                'short_description' => 'Next-generation privacy-first web traffic intelligence tool with click heatmaps, user funnel recordings, and core web vitals monitoring.',
                'description' => '<h3>Zero-Cookie High Fidelity Product Analytics</h3><p>PulseMetrics gives growth marketing teams actionable insights without degrading page load performance.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [],
                'item_type' => 'direct_link',
                'direct_url' => 'https://pulsemetrics.example.com',
                'youtube_video_url' => null,
                'client_name' => 'PulseMetrics SaaS',
                'completion_date' => 'March 2026',
                'tech_stacks' => ['ClickHouse', 'Laravel', 'React', 'Tailwind CSS', 'Chart.js'],
                'views_count' => 1100,
                'is_featured' => false,
                'order' => 7,
                'is_active' => true,
            ],
            [
                'category_id' => $ai,
                'title' => 'DeepVision AI Medical Diagnostic Suite',
                'slug' => 'deepvision-ai-medical-diagnostic-suite',
                'short_description' => 'Computer vision diagnostic suite for automated radiology scans and tumor segmentation with 98.6% clinical accuracy benchmark.',
                'description' => '<h3>Assisting Radiologists with AI Precision</h3><p>DeepVision accelerates MRI and CT scan analysis, automatically highlighting potential anomalies and reducing triage times by 70%.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://deepvision.example.med',
                'youtube_video_url' => 'https://www.youtube.com/watch?v=2vjPBrBU-TM',
                'client_name' => 'BioVision Diagnostics',
                'completion_date' => 'May 2026',
                'tech_stacks' => ['PyTorch', 'TensorRT', 'FastAPI', 'React', 'Tailwind CSS'],
                'views_count' => 2450,
                'is_featured' => true,
                'order' => 8,
                'is_active' => true,
            ],
            [
                'category_id' => $ecom,
                'title' => 'HyperBoutique Multi-Vendor Marketplace',
                'slug' => 'hyperboutique-multi-vendor-marketplace',
                'short_description' => 'Ultra-fast global artisan marketplace featuring instant vendor onboarding, automated split payments, and dynamic currency conversions.',
                'description' => '<h3>Empowering 10,000+ Independent Makers</h3><p>HyperBoutique enables creative craftsmen around the globe to launch independent digital storefronts within minutes.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://hyperboutique.example.com',
                'youtube_video_url' => null,
                'client_name' => 'HyperBoutique Ltd',
                'completion_date' => 'April 2026',
                'tech_stacks' => ['Laravel 12', 'Inertia.js', 'React', 'Stripe Connect', 'Tailwind CSS'],
                'views_count' => 780,
                'is_featured' => false,
                'order' => 9,
                'is_active' => true,
            ],
            [
                'category_id' => $landing,
                'title' => 'QuantumX Quantum Computing Marketing Site',
                'slug' => 'quantumx-quantum-computing-marketing-site',
                'short_description' => 'Sleek dark-mode agency landing page designed for a deep-tech quantum simulation startup with interactive quantum circuit builder demo.',
                'description' => '<h3>Explaining Deep Tech with Visual Simplicity</h3><p>QuantumX captivates prospective enterprise buyers with an interactive in-browser qubit simulation canvas and interactive benchmarks.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://quantumx.example.tech',
                'youtube_video_url' => null,
                'client_name' => 'QuantumX Technologies',
                'completion_date' => 'January 2026',
                'tech_stacks' => ['React', 'Vite', 'Tailwind CSS', 'Framer Motion', 'Canvas API'],
                'views_count' => 1920,
                'is_featured' => true,
                'order' => 10,
                'is_active' => true,
            ],
            [
                'category_id' => $fintech,
                'title' => 'ApexCapital Crypto Algorithmic Terminal',
                'slug' => 'apexcapital-crypto-algorithmic-terminal',
                'short_description' => 'Low-latency trading terminal with custom charting engines, WebSocket order book feeds, and automated risk management algorithms.',
                'description' => '<h3>High-Frequency Visual Execution</h3><p>Built for quantitative prop trading funds to execute and monitor cross-exchange arbitrage opportunities in milliseconds.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'direct_link',
                'direct_url' => 'https://tradingview.com',
                'youtube_video_url' => null,
                'client_name' => 'Apex Capital Partners',
                'completion_date' => 'February 2026',
                'tech_stacks' => ['TypeScript', 'TradingView Lightweight Charts', 'Rust Backend', 'WebSockets'],
                'views_count' => 1340,
                'is_featured' => false,
                'order' => 11,
                'is_active' => true,
            ],
            [
                'category_id' => $portals,
                'title' => 'LogiStream Global Freight ERP',
                'slug' => 'logistream-global-freight-erp',
                'short_description' => 'Container tracking, customs compliance automation, and IoT vessel sensor telemetry platform for maritime logistics.',
                'description' => '<h3>Transforming Global Supply Chain Visibility</h3><p>LogiStream provides maritime fleet operators with real-time GPS container tracking, automated bill-of-lading generation, and emissions compliance reporting.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://logistream.example.com',
                'youtube_video_url' => null,
                'client_name' => 'LogiStream Global Logistics',
                'completion_date' => 'March 2026',
                'tech_stacks' => ['Laravel 12', 'Inertia.js', 'React', 'Mapbox GL', 'MySQL'],
                'views_count' => 670,
                'is_featured' => false,
                'order' => 12,
                'is_active' => true,
            ],
            [
                'category_id' => $saas,
                'title' => 'DevSync Code Review & QA Orchestrator',
                'slug' => 'devsync-code-review-qa-orchestrator',
                'short_description' => 'Collaborative code intelligence tool that surfaces PR architectural bottlenecks, security vulnerabilities, and test coverage regressions.',
                'description' => '<h3>Accelerate Code Review Cycles by 50%</h3><p>DevSync integrates seamlessly with GitHub and GitLab, applying AI-powered static analysis and visual diff reviews.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://devsync.example.io',
                'youtube_video_url' => null,
                'client_name' => 'DevSync Systems',
                'completion_date' => 'April 2026',
                'tech_stacks' => ['React', 'Node.js', 'GraphQL', 'Tailwind CSS', 'Docker'],
                'views_count' => 1580,
                'is_featured' => true,
                'order' => 13,
                'is_active' => true,
            ],
            [
                'category_id' => $ai,
                'title' => 'VoiceMatrix Multilingual Speech Engine',
                'slug' => 'voicematrix-multilingual-speech-engine',
                'short_description' => 'Ultra-low latency real-time voice synthesis and voice cloning studio for interactive digital avatars and customer service bots.',
                'description' => '<h3>Hyper-Realistic Human Voice Generation</h3><p>VoiceMatrix delivers expressive neural speech generation in 60+ languages with emotional inflection control.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://voicematrix.example.ai',
                'youtube_video_url' => null,
                'client_name' => 'VoiceMatrix AI',
                'completion_date' => 'May 2026',
                'tech_stacks' => ['PyTorch', 'Web Audio API', 'React', 'FastAPI', 'Tailwind CSS'],
                'views_count' => 1890,
                'is_featured' => false,
                'order' => 14,
                'is_active' => true,
            ],
            [
                'category_id' => $landing,
                'title' => 'Solarix Clean Energy Product Showcase',
                'slug' => 'solarix-clean-energy-product-showcase',
                'short_description' => 'Modern solar battery and smart energy grid landing page with interactive residential solar savings calculator.',
                'description' => '<h3>Accelerating Renewable Energy Adoption</h3><p>Solarix features an intuitive calculator estimating annual energy savings based on user location and roof dimensions.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'in_app_link',
                'direct_url' => 'https://solarix.example.energy',
                'youtube_video_url' => null,
                'client_name' => 'Solarix Energy Inc.',
                'completion_date' => 'June 2026',
                'tech_stacks' => ['React', 'Inertia.js', 'Tailwind CSS', 'Chart.js'],
                'views_count' => 890,
                'is_featured' => false,
                'order' => 15,
                'is_active' => true,
            ],
            [
                'category_id' => $ecom,
                'title' => 'Zenith Minimalist Watchmaking Store',
                'slug' => 'zenith-minimalist-watchmaking-store',
                'short_description' => 'Bespoke mechanical timepiece configurator with 360-degree strap and dial customization.',
                'description' => '<h3>Swiss Precision Digital Experience</h3><p>Custom watch configurator with real-time 3D rendering and international shipping integration.</p>',
                'thumbnail' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
                ],
                'item_type' => 'direct_link',
                'direct_url' => 'https://zenith.example.watches',
                'youtube_video_url' => null,
                'client_name' => 'Zenith Horology',
                'completion_date' => 'January 2026',
                'tech_stacks' => ['Next.js', 'Three.js', 'Tailwind CSS', 'Stripe'],
                'views_count' => 1210,
                'is_featured' => false,
                'order' => 16,
                'is_active' => true,
            ],
        ];

        foreach ($portfolios as $item) {
            Portfolio::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
