<?php

namespace Database\Seeders;

use App\Models\SaasProduct;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SaasProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'CloudERP Suite Enterprise',
                'slug' => 'clouderp-suite-enterprise',
                'tagline' => 'All-in-one business management, telemetry, and automated workflow platform',
                'description' => 'Complete enterprise cloud solution featuring multi-branch inventory tracking, automated accounting, payroll, CRM pipelines, and real-time executive dashboard telemetry. Built on microservices architecture for ultra-high throughput and 99.99% SLA reliability.',
                'icon' => 'Database',
                'badge' => 'Most Popular',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=900&auto=format&fit=crop&q=80',
                ],
                'monthly_price' => 4999.00,
                'half_yearly_price' => 26999.00,
                'yearly_price' => 49999.00,
                'has_monthly' => true,
                'has_half_yearly' => true,
                'has_yearly' => true,
                'features' => [
                    'Multi-Branch Real-Time Inventory Tracking',
                    'Automated Accounting & Multi-Currency Invoicing',
                    'Role-Based RBAC Permissions & Audit Logs',
                    'Custom Domain with Managed Auto-SSL',
                    'Daily Automated Cloud Backups with 99.99% SLA',
                    'Priority 24/7 Dedicated Support Engineer',
                ],
                'packages' => [
                    'basic' => [
                        'name' => 'Basic Plan',
                        'tagline' => 'Essential ERP capabilities for single-location businesses and agile startups.',
                        'monthly_price' => 2999.00,
                        'yearly_price' => 29990.00,
                        'badge' => 'Starter Tier',
                        'is_popular' => false,
                        'features' => [
                            'Single Branch Inventory & Stock Management',
                            'Up to 5 Team Member Accounts',
                            'Automated Basic Invoicing & Sales Receipts',
                            'Standard Subdomain SSL (.codeventure.app)',
                            'Daily Automated Backups',
                            'Standard Email Ticket Support (24h response)',
                        ],
                    ],
                    'standard' => [
                        'name' => 'Standard Plan',
                        'tagline' => 'Our flagship enterprise package designed for multi-branch growing companies.',
                        'monthly_price' => 4999.00,
                        'yearly_price' => 49990.00,
                        'badge' => 'Most Popular',
                        'is_popular' => true,
                        'features' => [
                            'Multi-Branch Centralized Inventory Sync',
                            'Up to 25 Team Member Accounts with RBAC',
                            'Automated Multi-Currency Invoicing & Tax Calculation',
                            'Custom Domain Mapping with Complimentary SSL',
                            'Integrated bKash / Nagad Instant Billing API',
                            'Priority 24/7 Support with 1-Hour SLA',
                        ],
                    ],
                    'premium' => [
                        'name' => 'Premium Plan',
                        'tagline' => 'Full enterprise autonomy with dedicated cloud instances and VIP engineer onboarding.',
                        'monthly_price' => 8999.00,
                        'yearly_price' => 89990.00,
                        'badge' => 'Enterprise Suite',
                        'is_popular' => false,
                        'features' => [
                            'Unlimited Branches, Warehouses & User Accounts',
                            'Dedicated Isolated Cloud Database Instance',
                            'Custom ERP Workflows & Webhook Integrations',
                            'White-Label Branded Portal & Client Mobile App',
                            'Dedicated Senior Account Engineer On-Call',
                            '99.99% Uptime Guarantee & Custom Legal SLA',
                        ],
                    ],
                ],
                'order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'OmniStore E-Commerce Engine',
                'slug' => 'omnistore-ecommerce-engine',
                'tagline' => 'High-converting headless digital storefront with sub-second checkout',
                'description' => 'Ultra-scalable e-commerce SaaS architecture equipped with bKash/Nagad automated checkout, order fulfillment tracking, customer loyalty points, and flash sale acceleration.',
                'icon' => 'Globe',
                'badge' => 'High Growth',
                'thumbnail' => 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=900&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1556742049-0a67e557224f?w=900&auto=format&fit=crop&q=80',
                ],
                'monthly_price' => 3499.00,
                'half_yearly_price' => 18999.00,
                'yearly_price' => 34999.00,
                'has_monthly' => true,
                'has_half_yearly' => true,
                'has_yearly' => true,
                'features' => [
                    'Sub-second Global Page Load Speed (Core Web Vitals 99+)',
                    'Integrated bKash, Nagad, Card & Courier Gateway APIs',
                    'Abandoned Cart Recovery Automation & SMS Marketing',
                    'Custom Branded Domain with Free Managed CDN',
                    'Product Variant Matrix & Bulk Inventory Importer',
                    'Full Telemetry & Google Analytics 4 Ecommerce Tracking',
                ],
                'packages' => [
                    'basic' => [
                        'name' => 'Basic Plan',
                        'tagline' => 'Launch your online shop with lightning-fast hosted storefront.',
                        'monthly_price' => 2499.00,
                        'yearly_price' => 24990.00,
                        'badge' => 'Starter',
                        'is_popular' => false,
                        'features' => [
                            'Up to 500 Active Product SKUs',
                            'Standard Responsive E-Commerce Theme',
                            'Manual bKash / Nagad TrxID Verification',
                            'Integrated SteadFast & Pathao Courier Sync',
                            'Standard Subdomain SSL (.codeventure.app)',
                        ],
                    ],
                    'standard' => [
                        'name' => 'Standard Plan',
                        'tagline' => 'Accelerate sales with automated payment validation and marketing tools.',
                        'monthly_price' => 3499.00,
                        'yearly_price' => 34990.00,
                        'badge' => 'Best Value',
                        'is_popular' => true,
                        'features' => [
                            'Up to 5,000 Active Product SKUs & Variants',
                            'Automated bKash / Nagad Checkout Integration',
                            'Custom Branded Domain with Complimentary CDN',
                            'SMS Marketing & Abandoned Cart Recovery Bot',
                            'Coupon Engine, Flash Sales & Customer Loyalty Points',
                            'Priority 24/7 WhatsApp & Ticket Support',
                        ],
                    ],
                    'premium' => [
                        'name' => 'Premium Plan',
                        'tagline' => 'High-throughput architecture for top-tier retail brands and wholesale sellers.',
                        'monthly_price' => 6499.00,
                        'yearly_price' => 64990.00,
                        'badge' => 'Enterprise E-Com',
                        'is_popular' => false,
                        'features' => [
                            'Unlimited Product SKUs & Bulk CSV Importer',
                            'Headless Storefront with React 19 / Next.js Speed',
                            'Multi-Warehouse Fulfillment & Courier Automation',
                            'Custom Mobile App (Android APK Build Included)',
                            'Dedicated High-Volume Redis Cache Cluster',
                            'VIP 24/7 Dedicated Technical Architect',
                        ],
                    ],
                ],
                'order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Agentic AI Support Workspace',
                'slug' => 'agentic-ai-support-workspace',
                'tagline' => 'Autonomous customer support agent trained directly on your business documents',
                'description' => 'Deploy custom AI support bots that resolve 80%+ of incoming inquiries instantly on your website, WhatsApp, and social media channels using private RAG neural vectors and zero data leakage guarantee.',
                'icon' => 'Cpu',
                'badge' => 'AI Powered',
                'thumbnail' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=900&auto=format&fit=crop&q=80',
                ],
                'monthly_price' => 2999.00,
                'half_yearly_price' => 15999.00,
                'yearly_price' => 29999.00,
                'has_monthly' => true,
                'has_half_yearly' => true,
                'has_yearly' => true,
                'features' => [
                    'Unlimited Knowledge Base Vector Document Embeddings',
                    'Multi-Channel Bot Widget (Web, WhatsApp, Messenger)',
                    'Smart Fallback to Human Agents with Ticket Escalation',
                    'Custom LLM Prompt Fine-Tuning & Brand Voice Matching',
                    'Analytics on Popular Inquiries & Customer Sentiment',
                    'Zero Data Leakage Guarantee (Enterprise Isolated DB)',
                ],
                'packages' => [
                    'basic' => [
                        'name' => 'Basic Plan',
                        'tagline' => 'Automate basic customer FAQs and live chat on your website.',
                        'monthly_price' => 1999.00,
                        'yearly_price' => 19990.00,
                        'badge' => 'AI Starter',
                        'is_popular' => false,
                        'features' => [
                            'Up to 1,000 AI Conversations / Month',
                            'Embed on 1 Website with Customizable Widget',
                            'Upload up to 50 PDF / Doc Knowledge Base Files',
                            'Standard Human Ticket Escalation',
                            'Standard Email Support',
                        ],
                    ],
                    'standard' => [
                        'name' => 'Standard Plan',
                        'tagline' => 'Multi-channel support bot for website, WhatsApp, and social media.',
                        'monthly_price' => 2999.00,
                        'yearly_price' => 29990.00,
                        'badge' => 'Recommended',
                        'is_popular' => true,
                        'features' => [
                            'Up to 10,000 AI Conversations / Month',
                            'Website Widget + WhatsApp Business API Connector',
                            'Unlimited Knowledge Base Documents & URL Crawlers',
                            'Sentiment Analysis & Lead Capture Form Integration',
                            'Custom Bot Personality & Brand Voice Calibration',
                            'Priority 24/7 Support',
                        ],
                    ],
                    'premium' => [
                        'name' => 'Premium Plan',
                        'tagline' => 'Autonomous AI agents with custom API actions, CRM sync, and dedicated LLM inference.',
                        'monthly_price' => 5999.00,
                        'yearly_price' => 59990.00,
                        'badge' => 'AI Enterprise',
                        'is_popular' => false,
                        'features' => [
                            'Unlimited Conversations & High-Speed Neural Vectors',
                            'Autonomous Actions (Check Order Status, Book Appointments)',
                            'Full Multi-Channel (Web, WhatsApp, Messenger, Telegram)',
                            'Dedicated Isolated Vector Database (Zero Shared Memory)',
                            'Custom Fine-Tuning on Proprietary Datasets',
                            'Dedicated AI Solutions Architect',
                        ],
                    ],
                ],
                'order' => 3,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'SmartBookings & Client Portal',
                'slug' => 'smartbookings-client-portal',
                'tagline' => 'Frictionless appointment scheduling, service invoicing, and client management',
                'description' => 'Designed for agencies, clinics, consultants, and service providers. Automate client onboarding, video call link generation, upfront deposit collection, and calendar sync.',
                'icon' => 'Calendar',
                'badge' => 'Starter Choice',
                'thumbnail' => 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=900&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=900&auto=format&fit=crop&q=80',
                ],
                'monthly_price' => 1999.00,
                'half_yearly_price' => 10999.00,
                'yearly_price' => 19999.00,
                'has_monthly' => true,
                'has_half_yearly' => true,
                'has_yearly' => true,
                'features' => [
                    'Google Calendar & Outlook Two-Way Synchronization',
                    'Automated WhatsApp & SMS Reminder Notifications',
                    'Advance Deposit Collection via bKash / Nagad',
                    'Client Self-Service Rescheduling & Cancellation Window',
                    'Custom Form Builder for Pre-Appointment Questionnaires',
                    'Staff Calendar Management & Shift Scheduling',
                ],
                'packages' => [
                    'basic' => [
                        'name' => 'Basic Plan',
                        'tagline' => 'Simple booking page for individual freelancers and consultants.',
                        'monthly_price' => 1499.00,
                        'yearly_price' => 14990.00,
                        'badge' => 'Solo',
                        'is_popular' => false,
                        'features' => [
                            '1 Staff / Practitioner Calendar',
                            'Unlimited Client Bookings',
                            'Google Calendar 2-Way Synchronization',
                            'Automated Email Confirmation & Reminders',
                            'Subdomain Booking Portal (.codeventure.app)',
                        ],
                    ],
                    'standard' => [
                        'name' => 'Standard Plan',
                        'tagline' => 'Complete client portal with deposit collection and SMS reminders.',
                        'monthly_price' => 1999.00,
                        'yearly_price' => 19990.00,
                        'badge' => 'Top Pick',
                        'is_popular' => true,
                        'features' => [
                            'Up to 5 Staff Calendars & Shift Managers',
                            'Automated WhatsApp & SMS Reminders to Reduce No-Shows',
                            'bKash / Nagad Advance Deposit Collection',
                            'Custom Domain Mapping with SSL',
                            'Pre-Appointment Custom Questionnaires',
                            'Standard Ticket Support',
                        ],
                    ],
                    'premium' => [
                        'name' => 'Premium Plan',
                        'tagline' => 'Enterprise booking engine for clinics, multi-branch salons, and large agencies.',
                        'monthly_price' => 3999.00,
                        'yearly_price' => 39990.00,
                        'badge' => 'Pro Agency',
                        'is_popular' => false,
                        'features' => [
                            'Unlimited Staff Calendars & Branch Locations',
                            'Zoom & Google Meet Auto-Link Generation',
                            'Client Invoicing, Receipts & Packages Subscriptions',
                            'Staff Commission Tracking & Revenue Telemetry',
                            'VIP Custom Domain & White-Label Styling',
                            'Dedicated Account Engineer Support',
                        ],
                    ],
                ],
                'order' => 4,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'NexusPOS & Multi-Outlet Cloud Engine',
                'slug' => 'nexuspos-multi-outlet-engine',
                'tagline' => 'High-speed cloud POS billing, barcode scanner sync, and retail chain analytics',
                'description' => 'Ultra-fast retail and restaurant point-of-sale platform. Supports offline sales mode, thermal bluetooth receipt printing, kitchen order tickets, staff shift audits, and live revenue telemetry across branches.',
                'icon' => 'Layers',
                'badge' => 'Retail Specialist',
                'thumbnail' => 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=900&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1556742049-0a67e557224f?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1556741533-411cf82e4e2d?w=900&auto=format&fit=crop&q=80',
                ],
                'monthly_price' => 2499.00,
                'half_yearly_price' => 13499.00,
                'yearly_price' => 24999.00,
                'has_monthly' => true,
                'has_half_yearly' => true,
                'has_yearly' => true,
                'features' => [
                    'Lightning Fast Barcode Scan & Offline Mode Billing',
                    'Thermal Receipt & Bluetooth Printer Integration (ESC/POS)',
                    'Multi-Outlet Centralized Inventory Synchronization',
                    'Customer Loyalty Cash-Back & Discount Coupon Engine',
                    'Staff Shift Cash Drawer Reconciliations & Audit Trails',
                    'Real-Time Sales Telemetry on iOS & Android Mobile App',
                ],
                'packages' => [
                    'basic' => [
                        'name' => 'Basic Plan',
                        'tagline' => 'Ideal for single retail shop or boutique with rapid barcode checkout.',
                        'monthly_price' => 1799.00,
                        'yearly_price' => 17990.00,
                        'badge' => 'Single Shop',
                        'is_popular' => false,
                        'features' => [
                            '1 POS Terminal & Cash Register',
                            'Barcode Scanner & ESC/POS Thermal Printing',
                            'Unlimited Products & Invoices Created',
                            'Daily Sales Email Summary Report',
                            'Standard Support',
                        ],
                    ],
                    'standard' => [
                        'name' => 'Standard Plan',
                        'tagline' => 'Our flagship POS for growing multi-counter retail and restaurant outlets.',
                        'monthly_price' => 2499.00,
                        'yearly_price' => 24990.00,
                        'badge' => 'Most Popular',
                        'is_popular' => true,
                        'features' => [
                            'Up to 3 Counters / Branch Outlets',
                            'Offline Billing Mode with Automatic Cloud Sync',
                            'Kitchen Display System (KDS) & Order Tickets',
                            'Customer Loyalty Points & Discount Matrix',
                            'Staff Shift Reconciliations & Cash Audit Trails',
                            'Priority 24/7 Support',
                        ],
                    ],
                    'premium' => [
                        'name' => 'Premium Plan',
                        'tagline' => 'Complete retail chain ERP integration with centralized warehouse sync.',
                        'monthly_price' => 4999.00,
                        'yearly_price' => 49990.00,
                        'badge' => 'Chain Enterprise',
                        'is_popular' => false,
                        'features' => [
                            'Unlimited Branch Outlets & POS Counters',
                            'Centralized Warehouse Distribution Logistics',
                            'Live Mobile Telemetry App for Owners (iOS / Android)',
                            'Automated bKash QR Dynamic Billing Integration',
                            'Dedicated High-Availability Database Cluster',
                            'Dedicated On-Site & Remote Account Manager',
                        ],
                    ],
                ],
                'order' => 5,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'DevFlow Cloud CI/CD Pipeline',
                'slug' => 'devflow-cloud-cicd-pipeline',
                'tagline' => 'Automated deployment pipelines, Docker container registry, and preview environments',
                'description' => 'Fast, modern cloud deployment platform tailored for software agencies and developer teams. Connect your GitHub/GitLab repositories for instant pull request preview deployments, automated testing, and zero-downtime rolling updates.',
                'icon' => 'Server',
                'badge' => 'DevOps Favorite',
                'thumbnail' => 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=900&auto=format&fit=crop&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=900&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&auto=format&fit=crop&q=80',
                ],
                'monthly_price' => 3999.00,
                'half_yearly_price' => 21999.00,
                'yearly_price' => 39999.00,
                'has_monthly' => true,
                'has_half_yearly' => true,
                'has_yearly' => true,
                'features' => [
                    'Automated GitHub & GitLab Webhook Triggers',
                    'Ephemeral PR Preview Environments with Auto-SSL',
                    'Private Docker Image Registry & Vulnerability Scanning',
                    'Zero-Downtime Rolling & Blue-Green Deployments',
                    'Custom Secrets Management & Environment Isolation',
                    'Live Container Log Streaming & Telemetry Graphs',
                ],
                'packages' => [
                    'basic' => [
                        'name' => 'Basic Plan',
                        'tagline' => 'For individual software developers and early stage side projects.',
                        'monthly_price' => 1999.00,
                        'yearly_price' => 19990.00,
                        'badge' => 'Hobbyist',
                        'is_popular' => false,
                        'features' => [
                            'Up to 3 Connected Git Repositories',
                            '500 Build Minutes / Month on Shared Runners',
                            'Auto SSL Deployment on Subdomains',
                            '1 Concurrency Pipeline Slot',
                            'Standard Community & Ticket Support',
                        ],
                    ],
                    'standard' => [
                        'name' => 'Standard Plan',
                        'tagline' => 'Fast pipelines and preview branches for agile agency engineering squads.',
                        'monthly_price' => 3999.00,
                        'yearly_price' => 39990.00,
                        'badge' => 'Team Standard',
                        'is_popular' => true,
                        'features' => [
                            'Up to 15 Connected Git Repositories',
                            '2,500 High-Speed Build Minutes / Month',
                            'Ephemeral Pull Request Preview Deployments',
                            'Private Docker Container Registry (50 GB)',
                            '3 Concurrent Pipeline Slots',
                            'Priority 24/7 Technical Ticket Support',
                        ],
                    ],
                    'premium' => [
                        'name' => 'Premium Plan',
                        'tagline' => 'Dedicated Kubernetes runners, unlimited build minutes, and custom cloud VPC mapping.',
                        'monthly_price' => 7999.00,
                        'yearly_price' => 79990.00,
                        'badge' => 'DevOps Enterprise',
                        'is_popular' => false,
                        'features' => [
                            'Unlimited Git Repositories & Unlimited Build Minutes',
                            'Dedicated Bare-Metal Runners with Turbo Cache',
                            'Custom Cloud VPC & On-Premises Kubernetes Cluster Sync',
                            'SOC2 Compliance Audit Trails & Granular RBAC',
                            '10 Concurrent Pipeline Slots',
                            'Dedicated Site Reliability Engineer (SRE) On-Call',
                        ],
                    ],
                ],
                'order' => 6,
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $p) {
            SaasProduct::updateOrCreate(['slug' => $p['slug']], $p);
        }
    }
}
